### ISSUE TITLE
Site specific permissions are not shown in the popup UI

### ISSUE THREAD

**Issue by holantonela** [MetaMask/snaps-skunkworks#305]
We currently exposed which site is connected to the Snap accessible via `home.html#settings/snaps-list`.

It seems expected that we also reflect that interaction in the popover UI.

<img width="1265" alt="Screenshot 2022-03-21 at 12 30 52" src="https://user-images.githubusercontent.com/87079938/159270824-758e017d-69ab-4ac4-a4f9-08fba5b64e70.png">

**Comment by FrederikBolding** [comment]
We can easily detect that the origin is connected to a snap (I already wrote code for this). My only question would be what to show in the popover then and is it confusing that we use this UI which also normally shows whether an account is connected to a page.

cc @rekmarks

**Comment by FrederikBolding** [comment]
Also @holantonela are you on an old build? On the current version I see the permissions: 
![image](https://user-images.githubusercontent.com/1561200/159513117-36cfcefb-8f3f-4ba7-b576-bcb77007e670.png)

**Comment by rekmarks** [comment]
So @holantonela's screenshot might be from prod or a slightly older build, because we did have a bug where the list was not properly populated. I think we definitely want to show the complete list of permissions for the website, and the original extension designs for this component were made with exactly this use case (multiple different permissions) in mind.

IMO, the unresolved question is whether we want the "connected" indicator to become green for any permission or just `eth_accounts`. This is a design question that I will leave for @holantonela and @rachelcope.

**Comment by FrederikBolding** [comment]
The copy is interesting then. It seems weird to me to show "MetaMask is not connected to this site....." and then show the permissions the origin has. It might just be me though 🤷‍♂️

**Comment by rekmarks** [comment]
We may want to switch the copy, but IIRC the meaning of "connected" is flexible enough to support our use case.

**Comment by rekmarks** [comment]
We will close this issue because snap permissions _are_ displayed in the list. There are other unresolved questions regarding snap permissions in the current extension UI, but those will be covered in other issues.
