### ISSUE TITLE
The method `snap_notify` does not exist / is not available.

### ISSUE THREAD

**Issue by anudit** [MetaMask/snaps-skunkworks#315]
Running into the following error on the latest release `^0.10.6`, 

![image](https://user-images.githubusercontent.com/12015553/159473553-909ddb59-97e9-4a32-ac9c-de9a0a673793.png)

![image](https://user-images.githubusercontent.com/12015553/159473604-337ae6ff-4d45-4ab0-bef5-aba80d75f061.png)

Snap Codebase for reproduction: https://github.com/anudit/omnidsnap

cc: @FrederikBolding

**Comment by FrederikBolding** [comment]
@anudit are you using MM Flask from the Chrome store or built locally?

We are currently working on getting the latest changes shipped in a new version of MM Flask, but it is not live on the Chrome store yet!

If you are not running MM built locally and is comfortable doing so you can find instructions on doing that here: https://github.com/MetaMask/metamask-extension

Otherwise, hang on for a bit while we get the next version of MetaMask Flask released!

**Comment by anudit** [comment]
@FrederikBolding Currently using the latest version `10.8.2-flask.2` on the Chrome Webstore. 

Got it, will build from source, Thanks!
