### ISSUE TITLE
Reinstalling a snap after it has installed another snap with `wallet_enable` causes Error when adding snap. Error: Action missing from allow list: PermissionController:revokePermissions

### ISSUE THREAD

**Issue by ziad-saab** [MetaMask/snaps-skunkworks#704]
Steps to reproduce:

1. Create a Snap A which, in one of its RPC methods, installs a second snap B using `wallet_enable`
2. From a dapp, install Snap A using `wallet_enable`
3. From the dapp, call Snap A's method which installs snap B
4. Try to reinstall Snap A using the same `wallet_enable` call
5. In the `background.html` console of MetaMask Flask, note the following error:
    ```
    Error when adding snap. Error: Action missing from allow list: PermissionController:revokePermissions
      at i.call (common-0.js:1:241997)
      at k.authorize (background-1.js:22:38316)
      at async k.processRequestedSnap (background-1.js:22:32309)
      at async background-1.js:22:31100
      at async Promise.all (index 0)
      at async k.installSnaps (background-1.js:22:30859)
      at async r.handleInstallSnaps (background-0.js:1:142280)
      at async implementation (background-0.js:1:143658)
      at async background-8.js:1:5025
    ```

The [Snapquanow Demo](https://github.com/ziad-saab/snapquanow-demo) repo can be used as an example of "Snap A" in this case. It will install [Snapquanow](https://github.com/ziad-saab/snapquanow), which would be Snap B in the description above.

**Comment by FrederikBolding** [comment]
Thanks for reporting this!

This bug should already be fixed in the extension `develop` branch as of this commit: https://github.com/MetaMask/metamask-extension/commit/a7179a6b88e0886217c3341a0c07dda6b325e231

If you are comfortable with building MetaMask yourself, you can build and run the `develop` branch for the latest changes, by following the README here: https://github.com/MetaMask/metamask-extension

To run Flask you can use `yarn start --build-type=flask`.

If you are not comfortable with this, we'll publish a new version of Flask within the next few weeks that contains this fix.
